/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nexlink.server.gui;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author ALI
 */
public class ServerConsole extends javax.swing.JFrame {
    
    private static ServerConsole instance;
    private static final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServerConsole.class.getName());

    /**
     * Creates new form ServerConsole
     */
    public ServerConsole() {
        initComponents();
        instance = this;

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jTextPane1.setOpaque(false);
        jTextPane1.setEditable(false);
        // Optional: Make sure the text is bright white or green so it's readable on your dark background
        jTextPane1.setForeground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("NEXLINK NETWORK CORE INSTANCE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 330, 40));

        jTextPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTextPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextPane1.setOpaque(false);
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 440, 583));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nexlink/server/gui/images/bck.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 520, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static void log(String type, String message) {
        if (instance == null) return;
        
        String timestamp = "[" + dtf.format(LocalDateTime.now()) + "]";
        String logLine = String.format("%s [%s] %s\n", timestamp, type.toUpperCase(), message);
        
        // Use invokeLater to prevent thread collision with the Swing UI thread
        java.awt.EventQueue.invokeLater(() -> {
            // Appends the text safely to your NetBeans text component
            String currentText = instance.jTextPane1.getText();
            instance.jTextPane1.setText(currentText + logLine);
            
            // Forces the scrollpane to slide down automatically to the newest log
            instance.jTextPane1.setCaretPosition(instance.jTextPane1.getDocument().getLength());
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServerConsole().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
