/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nexlink.client.auth;

import nexlink.client.auth.LoginScreenLogic;

/**
 *
 * @author ALI
 */
public class LoginScreen extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginScreen.class.getName());
    LoginScreenLogic loginScreenLogic;

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen(LoginScreenLogic logic) {
        
        
        initComponents();
        feildUserName.setOpaque(false);
        feildPassword.setOpaque(false);
        feildUserName.setForeground(java.awt.Color.WHITE);
        feildPassword.setForeground(java.awt.Color.WHITE);
        feildUserName.setBackground(new java.awt.Color(0, 0, 0, 0));
        feildPassword.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtDonotHaveAcc.setForeground(java.awt.Color.WHITE);
        feildUserName.setCaretColor(java.awt.Color.WHITE);
        feildPassword.setCaretColor(java.awt.Color.WHITE);

        this.loginScreenLogic = logic;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        feildUserName = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        feildPassword = new javax.swing.JPasswordField();
        title = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        txtDonotHaveAcc = new javax.swing.JLabel();
        buttonRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        feildUserName.setBackground(new java.awt.Color(255, 255, 255));
        feildUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        feildUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        feildUserName.addActionListener(this::feildUserNameActionPerformed);
        getContentPane().add(feildUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 95, 270, 30));

        userLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("UserName");
        getContentPane().add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 98, -1, -1));

        passLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passLabel.setForeground(new java.awt.Color(255, 255, 255));
        passLabel.setText("Password");
        getContentPane().add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 180, -1, 30));

        feildPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        feildPassword.setPreferredSize(new java.awt.Dimension(100, 40));
        feildPassword.addActionListener(this::feildPasswordActionPerformed);
        getContentPane().add(feildPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 270, 30));

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 189, 189));
        title.setText("USER LOGIN");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        buttonLogin.setBackground(new java.awt.Color(0, 255, 255));
        buttonLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(0, 0, 0));
        buttonLogin.setText("Login");
        buttonLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonLogin.setFocusable(false);
        buttonLogin.addActionListener(this::buttonLoginActionPerformed);
        getContentPane().add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 80, 30));

        txtDonotHaveAcc.setBackground(new java.awt.Color(255, 255, 255));
        txtDonotHaveAcc.setText("Do not have an Account?");
        getContentPane().add(txtDonotHaveAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        buttonRegister.setBackground(new java.awt.Color(0, 255, 255));
        buttonRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonRegister.setForeground(new java.awt.Color(0, 0, 0));
        buttonRegister.setText("Register");
        buttonRegister.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonRegister.setFocusable(false);
        buttonRegister.addActionListener(this::buttonRegisterActionPerformed);
        getContentPane().add(buttonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 283, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nexlink/client/auth/images/background.JPG"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:

        loginScreenLogic.setUsername(feildUserName.getText().trim());
        loginScreenLogic.setPassword(feildPassword.getText().trim());
        synchronized (loginScreenLogic.lock) {
            loginScreenLogic.lock.notify(); //Tells Client.java to stop waiting!
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void feildUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feildUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feildUserNameActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        // TODO add your handling code here:

        synchronized (loginScreenLogic.lock) {
            loginScreenLogic.lock.notify();
            loginScreenLogic.isRegisterTriggered = true;
        }
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void feildPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feildPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feildPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Pass a dummy or fresh logic instance so the template compiles safely
            new LoginScreen(new LoginScreenLogic()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JPasswordField feildPassword;
    private javax.swing.JTextField feildUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel txtDonotHaveAcc;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
