/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nexlink.client.auth;

import java.awt.Color;
/**
 *
 * @author ALI
 */
public class RegisterScreen extends javax.swing.JFrame {
    RegisterScreenLogic registerScreenLogic= new RegisterScreenLogic();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterScreen.class.getName());

    /**
     * Creates new form RegisterScreen
     */
    public RegisterScreen(RegisterScreenLogic registerScreenLogic) {
         
        this.registerScreenLogic= registerScreenLogic;
        
        initComponents();
        txtUserName.setOpaque(false);
        txtPassword.setOpaque(false);
        txtUserName.setForeground(java.awt.Color.WHITE);
        txtPassword.setForeground(java.awt.Color.WHITE);
        txtUserName.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtPassword.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtUserName.setCaretColor(java.awt.Color.WHITE);
        txtPassword.setCaretColor(java.awt.Color.WHITE);
        labelUsername.setForeground(Color.WHITE);
        labelPassword.setForeground(Color.WHITE);
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 189, 189));
        jLabel1.setText("Register User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 22, -1, -1));

        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelUsername.setText("User Name");
        getContentPane().add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 106, -1, -1));

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPassword.setText("Password");
        getContentPane().add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 217, -1, -1));

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserName.addActionListener(this::txtUserNameActionPerformed);
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 105, 270, 30));

        registerButton.setBackground(new java.awt.Color(0, 204, 204));
        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerButton.setForeground(new java.awt.Color(0, 0, 0));
        registerButton.setText("Register");
        registerButton.addActionListener(this::registerButtonActionPerformed);
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 289, -1, 37));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 216, 270, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nexlink/client/auth/images/background.JPG"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:

        String username = txtUserName.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();



        if (username.length() < 3 || password.length() < 3) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Username and Password must both be at least 3 characters long!",
                    "Registration Failed",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;

        }
        registerScreenLogic.setUsername(username);
        registerScreenLogic.setPassword(password);

        synchronized (registerScreenLogic.lock) {

            registerScreenLogic.lock.notify();
        }

    }//GEN-LAST:event_registerButtonActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            
            new RegisterScreen(new RegisterScreenLogic()).setVisible(true);
        
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JButton registerButton;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}