/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nexlink.client.gui;

import java.io.BufferedReader;
import java.io.BufferedWriter;

/**
 *
 * @author ALI
 */
public class ChatWindow extends javax.swing.JFrame {

    private void requestUserList() {
        try {
            // Send a custom string token to tell the server we need the user directory
            bufferedWriter.write("REQ_USER_LIST");
            bufferedWriter.newLine();
            bufferedWriter.flush();
        } catch (java.io.IOException e) {
            System.out.println("Error requesting user list: " + e.getMessage());
        }
    }

    private String currentLoggedInUser;
    private BufferedWriter bufferedWriter;
    private BufferedReader bufferedReader;
    private String selectedReceiver = null;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChatWindow.class.getName());

    /**
     * Creates new form ChatWindow
     */
public ChatWindow(String Username, BufferedWriter writer, BufferedReader reader) {

    this.currentLoggedInUser = Username;
    this.bufferedWriter = writer;
    this.bufferedReader = reader;

    initComponents();

    userList.setCellRenderer(new StatusListRenderer());

    messagesTextArea.setEditable(false);
    requestUserList();

    userList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        @Override
        public void valueChanged(javax.swing.event.ListSelectionEvent e) {
            // getValueIsAdjusting() ensures this only fires once per click (on mouse release)
            if (!e.getValueIsAdjusting()) {
                String selected = userList.getSelectedValue();
                if (selected != null) {
                    
                    // 💡 1. Strip out status tags (e.g., "wardan (offline)" -> "wardan")
                    String cleanReceiver = selected.split(" ")[0].trim();
                    selectedReceiver = cleanReceiver;

                    System.out.println("Target receiver changed to: " + selectedReceiver);
                    
                    try {
                        // 💡 2. Wipe the main chat area clean so old chat tracks don't bleed over
                        messagesTextArea.setText(""); 
                        
                        // 💡 3. Fire the request packet down the stream to your server
                        // Protocol format: REQ_HISTORY|TargetReceiverName
                        bufferedWriter.write("REQ_HISTORY|" + selectedReceiver);
                        bufferedWriter.newLine();
                        bufferedWriter.flush();
                        
                        System.out.println("🔄 Sent request to server for history with: " + selectedReceiver);
                        
                    } catch (Exception ex) {
                        System.out.println("❌ Client error requesting chat history: " + ex.getMessage());
                    }
                }
            }
        }
    });
}

    public javax.swing.JList<String> getUserList() {
        return userList;
    }

    public javax.swing.JTextPane getMessagesTextArea() {
        return messagesTextArea;
    }

    public String getSelectedReceiver() {
        return selectedReceiver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        nexLinkLabel = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();
        msgToSndTextFeild = new java.awt.TextField();
        leftPane = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        rightPane = new javax.swing.JScrollPane();
        messagesTextArea = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nexLinkLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nexLinkLabel.setForeground(new java.awt.Color(0, 204, 204));
        nexLinkLabel.setText("NexLink");
        jPanel1.add(nexLinkLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 147, -1));

        sendButton.setBackground(new java.awt.Color(0, 153, 153));
        sendButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setLabel("SEND");
        sendButton.addActionListener(this::sendButtonActionPerformed);
        jPanel1.add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 80, 40));

        msgToSndTextFeild.setBackground(new java.awt.Color(51, 51, 51));
        msgToSndTextFeild.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        msgToSndTextFeild.setForeground(new java.awt.Color(255, 255, 255));
        msgToSndTextFeild.addActionListener(this::msgToSndTextFeildActionPerformed);
        jPanel1.add(msgToSndTextFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 470, 40));

        userList.setBackground(new java.awt.Color(51, 51, 51));
        userList.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        userList.setForeground(new java.awt.Color(255, 255, 255));
        userList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        userList.setSelectionBackground(new java.awt.Color(102, 102, 102));
        userList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        userList.addListSelectionListener(this::userListValueChanged);
        leftPane.setViewportView(userList);

        jPanel1.add(leftPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 183, 423));

        messagesTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPane.setViewportView(messagesTextArea);

        jPanel1.add(rightPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 63, 570, 360));

        jLabel2.setBackground(new java.awt.Color(102, 0, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText(currentLoggedInUser);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 18, 288, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msgToSndTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgToSndTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgToSndTextFeildActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here
        String messageText = msgToSndTextFeild.getText().trim();

        // 1. Validation checks
        if (messageText.isEmpty()) {
            return;
        }

        if (selectedReceiver == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a user from the list to chat with.");
            return;
        }

        try {
            // 2. Package the data using our protocol structure: MSG|Receiver|Text
            bufferedWriter.write("MSG|" + selectedReceiver + "|" + messageText);
            bufferedWriter.newLine();
            bufferedWriter.flush();

            // 3. Clear out the text input field for the next message
            msgToSndTextFeild.setText("");

            // Optional: Append your own sent message directly to your messagesTextArea right away
            messagesTextArea.setText(messagesTextArea.getText() + "\nYou: " + messageText);

        } catch (java.io.IOException e) {
            System.out.println("Error sending message: " + e.getMessage());
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void userListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_userListValueChanged
        // TODO add your handling code here:

        String selected = userList.getSelectedValue();

        if (selected != null) {
            //  Clean up the display string to isolate just the pure username
            if (selected.contains(" (online)")) {
                selectedReceiver = selected.replace(" (online)", "");
            } else if (selected.contains(" (offline)")) {
                selectedReceiver = selected.replace(" (offline)", "");
            } else {
                selectedReceiver = selected;
            }

            System.out.println("👉 Target receiver changed to: " + selectedReceiver);
        }
    }//GEN-LAST:event_userListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane leftPane;
    private javax.swing.JTextPane messagesTextArea;
    private java.awt.TextField msgToSndTextFeild;
    private javax.swing.JLabel nexLinkLabel;
    private javax.swing.JScrollPane rightPane;
    private javax.swing.JButton sendButton;
    private javax.swing.JList<String> userList;
    // End of variables declaration//GEN-END:variables
}
